development:
  adapter: postgres
  database: dev
  pool: 5
  timeout: 5000
test:
  adapter: postgres
  database: test
  pool: 5
  timeout: 5000

production:
  adapter: postgres
  encoding: utf8
  database: prod
  pool: 5
