development:
  adapter: postgresql
  database: react_rails_test_dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: react_rails_test_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: react_rails_test_prod
  pool: 5
  timeout: 5000