development:
  adapter: mysql2
  database: lookstaging
  pool: 5
  timeout: 5000
test:
  adapter: mysql2
  database: lookstaging
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  database: lookstaging
  socket: /tmp/mysql.sock
  pool: 5
  timeout: 5000